In [1]:
import random

# random number from 0 to 1
print(random.random())
# Output 0.16123124494385477

# random number from 10 to 20
print(random.randint(10, 20))
# Output 18

# random number from 10 to 20 with step 2
print(random.randrange(10, 20, 2))
# Output 14

# random float number within a range
print(random.uniform(5.5, 25.5))
# Output 5.86390810771935

# random choice from sequence
print(random.choice([10, 20, 30, 40, 50]))
# Output 30

# random sample from sequence
print(random.sample([10, 20, 30, 40, 50], k=3))
# Output [50, 10, 20]

# random sample without replacement
print(random.choices([10, 20, 30, 40, 50], k=3))
# Output [30, 10, 40]

# random shuffle
x = [10, 20, 30, 40, 50, 60]
random.shuffle(x)
print(x)
# [60, 10, 30, 20, 50, 40]

# random seed
random.seed(2)
print(random.randint(10, 20))
# 10
random.seed(2)
print(random.randint(10, 20))
# 10


0.20686139806155035
11
18
24.83279789900162
10
[50, 20, 40]
[10, 50, 50]
[40, 10, 60, 30, 20, 50]
10
10


In [2]:
import random
print("floating point triangular")
print(random.triangular(10.5, 25.5, 5.5))
# Output 16.114862085401924

floating point triangular
8.991681982149789


In [3]:
import random

number_list = [3, 6, 9, 12, 15, 18, 21, 24, 27, 30]

print("First Sample is ", random.sample(number_list, k=5))
# Output [3, 27, 21, 24, 18]

# Get current state and store
state = random.getstate()
# set current state
random.setstate(state)

# Now it will print the same second sample list
print("Second Sample is ", random.sample(number_list, k=5))
# Output [3, 27, 21, 24, 18]

random.setstate(state)
# again it will print the same sample list again
print("Third Sample is ", random.sample(number_list, k=5))
# Output [3, 27, 21, 24, 18]

# Without setstate
# Gives new sample
print("Fourth Sample is ", random.sample(number_list, k=5))
# output [27, 24, 12, 21, 15]

First Sample is  [18, 9, 15, 27, 24]
Second Sample is  [12, 3, 9, 30, 18]
Third Sample is  [12, 3, 9, 30, 18]
Fourth Sample is  [21, 27, 18, 15, 12]


In [4]:
import numpy as np

random_array = np.random.rand(2, 2)
print("2x2 array for random numbers", random_array, "\n")

random_float_array = np.random.uniform(25.5, 99.5, size=(3, 2))
print("3 X 2 array of random float numbers in range [25.5, 99.5]", random_float_array)

2x2 array for random numbers [[0.6551195  0.06564129]
 [0.23794473 0.34397593]] 

3 X 2 array of random float numbers in range [25.5, 99.5] [[85.748759   41.26777762]
 [78.54028985 90.6488088 ]
 [56.55444843 85.32331256]]


In [5]:
import numpy as np

random_integer_array = np.random.random_integers(5, size=(3, 2))
print("2-dimensional random integer array", random_integer_array)

2-dimensional random integer array [[2 4]
 [2 4]
 [1 5]]


C:\Users\blokes\AppData\Local\Temp\ipykernel_22384\3424803676.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  random_integer_array = np.random.random_integers(5, size=(3, 2))


In [6]:
import uuid

# get a random UUID
safeId = uuid.uuid4()
print("safe unique id is ", safeId)

safe unique id is  7862c3a5-e220-401b-bfea-8a6d01bf8d55


In [7]:
import random

PlayerOne = "Eric"
PlayerTwo = "Kelly"

EricScore = 0
KellyScore = 0

# each dice contains six numbers
diceOne = [1, 2, 3, 4, 5, 6]
diceTwo = [1, 2, 3, 4, 5, 6]


def shuffle_dice():
    # Both Eric and Kelly will roll both the dices using shuffle method

    for i in range(5):
        # shuffle both the dice 5 times
        random.shuffle(diceOne)
        random.shuffle(diceTwo)
    # use choice method to pick one number randomly
    firstNumber = random.choice(diceOne)
    SecondNumber = random.choice(diceTwo)
    return firstNumber + SecondNumber


print("Dice game using a random module\n")

# Let's play Dice game three times
for i in range(3):
    # let's do toss to determine who has the right to play first
    # generate random number from 1 to 100. including 100
    EricTossNumber = random.randint(1, 100)
    # generate random number from 1 to 100. doesn't including 101
    KellyTossNumber = random.randrange(1, 101, 1)

    if (EricTossNumber > KellyTossNumber):
        print("Eric won the toss")
        EricScore = shuffle_dice()
        KellyScore = shuffle_dice()
    else:
        print("Kelly won the toss")
        KellyScore = shuffle_dice()
        EricScore = shuffle_dice()

    if (EricScore > KellyScore):
        print("Eric is winner of dice game. Eric's Score is:", EricScore, "Kelly's score is:", KellyScore, "\n")
    else:
        print("Kelly is winner of dice game. Kelly's Score is:", KellyScore, "Eric's score is:", EricScore, "\n")

Dice game using a random module

Eric won the toss
Kelly is winner of dice game. Kelly's Score is: 7 Eric's score is: 3 

Kelly won the toss
Eric is winner of dice game. Eric's Score is: 6 Kelly's score is: 3 

Kelly won the toss
Kelly is winner of dice game. Kelly's Score is: 8 Eric's score is: 4 



In [8]:
import random

# random integer from 0 to 9
num1 = random.randint(0, 9)
print(num1)
# output 5

# Random integer from 10 to 100
num2 = random.randint(10, 100)
print(num2)
# Output 84

3
61


In [9]:
import random

# random integer from 0 to 9
num1 = random.randint(0, 9)
print(num1)
# output 5

# Random integer from 10 to 100
num2 = random.randint(10, 100)
print(num2)
# Output 84

5
83


In [10]:
import random

# random number of length 4
num1 = random.randint(1000, 9999)
# random number of length 4 with step 2

num2 = random.randrange(1000, 10000, 2)
print(num1, num2)

# Output 3457 5116

3371 8644


In [11]:
import random

num = random.randrange(3, 300, 3)
print(num)
# output 144

171


In [12]:
import random

singed_int = random.randrange(-60, -6)
print(singed_int)
# Output -16

-14


In [13]:
import random

for i in range(5):
    print(random.randint(-10, 10), end=' ')
# Output 10 -1 5 -10 -7

-10 9 2 -5 2 

In [14]:
import random

num = random.choice([-1, 1])
print(num)

-1


In [15]:
import random

random_list = []
# Set a length of the list to 10
for i in range(0, 10):
    # any random numbers from 0 to 1000
    random_list.append(random.randint(0, 1000))
print(random_list)
# Output [994, 287, 65, 994, 936, 462, 839, 160, 689, 624]

[494, 280, 414, 259, 727, 748, 959, 422, 722, 663]


In [16]:
import random

# Generate 10 unique random numbers within a range
num_list = random.sample(range(0, 1000), 10)
print(num_list)
# Output [499, 580, 735, 784, 574, 511, 704, 637, 472, 211]

[483, 368, 985, 560, 338, 730, 763, 933, 674, 83]


In [17]:
import random

sample_list = random.sample(range(50, 500, 5), 5)
# Before sorting
print(sample_list)
# Output [305, 240, 260, 235, 445]

sample_list.sort()
# After sorting
print(sample_list)
# Output [235, 240, 260, 305, 445]

[190, 390, 445, 170, 305]
[170, 190, 305, 390, 445]


In [18]:
import secrets

# secure random integer
# from 0 to 10
secure_num = secrets.randbelow(10)
print(secure_num)
# Output 5

8


In [19]:
import numpy

# 4 x 4 array
newArray = numpy.random.randint(10, 50, size=(4, 4))
print(newArray)

[[14 23 33 10]
 [26 16 24 31]
 [39 12 12 15]
 [18 46 23 36]]


In [20]:
import numpy

# 3 x 5 array of ints
newArray = numpy.random.random_integers(60, 100, size=(3, 5))
print(newArray)

[[89 86 67 70 71]
 [72 62 86 91 81]
 [73 62 68 66 79]]


C:\Users\blokes\AppData\Local\Temp\ipykernel_22384\1388901416.py:4: DeprecationWarning: This function is deprecated. Please call randint(60, 100 + 1) instead
  newArray = numpy.random.random_integers(60, 100, size=(3, 5))


In [23]:
import random

# ValueError: empty range for randrange()
print(random.randrange(100, 10, 2))

ValueError: empty range in randrange(100, 10, 2)

In [24]:
import random

print(random.randrange(100, 10, -2))
# output 60

16


In [25]:
import random

movie_list = ['The Godfather', 'The Wizard of Oz', 'Citizen Kane', 'The Shawshank Redemption', 'Pulp Fiction']

# pick a random element from a list of strings.
movie = random.choice(movie_list)
print(movie)

The Shawshank Redemption


In [27]:
import random

num_list = [10, 15, 20, 25, 30]
random_index = random.randint(0, len(num_list) - 1)
random_element = num_list[random_index]
print('Random Number:', random_element)


Random Number: 10


In [28]:
import random

# sampling with replacement
original_list = [20, 30, 40, 50, 60, 70, 80]

# k = number of items to select
sample_list = random.choices(original_list, k=3)
print(sample_list)

# Output [60, 20, 60]

[40, 50, 80]


In [29]:
import random

sample_set = {20, 35, 45, 65, 82}
item = random.choice(tuple(sample_set))
# random item from set
print(item)
# Output 65

20


In [30]:
import random

# Choose randomly number from range of 10 to 100
num = random.choice(range(10, 101))
print(num)
# Output 93

93


In [31]:
import random

res = random.choice([True, False])
print(res)
# Output True

True


In [32]:
import random

# get random boolean
res = random.getrandbits(1)
print(bool(res))
# Output False

True


In [33]:
import random

atuple = (20, 30, 4)
# Random choice from a tuple
num = random.choice(atuple)
print(num)
# Output 30

20


In [34]:
import random

weight_dict = {
    "Kelly": 50,
    "Red": 68,
    "Scott": 70,
    "Emma": 40
}
# random key
key = random.choice(list(weight_dict))
# fetch value using key name
print("Random key-value pair is ", key, ":", weight_dict[key])
# Output Random key-value pair is  Red : 68

Random key-value pair is  Kelly : 50


In [35]:
from random import randrange

movie_list = ['The Godfather', 'The Wizard of Oz', 'Citizen Kane', 'The Shawshank Redemption', 'Pulp Fiction']

# get random index number
i = randrange(len(movie_list))
item = movie_list[i]
# Select item using index number
print("Randomly selected item", movie_list[i], "is present at index:", i)

# Output Randomly selected item Citizen Kane is present at index: 2

Randomly selected item The Shawshank Redemption is present at index: 3


In [36]:
import random

list_one = ["Thomas", "Liam", "William"]
list_two = ["Emma", "Olivia", "Isabella"]

seqs = list_one, list_two

# Random item  from two lists
item = random.choice(random.choices(seqs, weights=map(len, seqs))[0])
print(item)
# Output William

Isabella


In [42]:
import numpy as np

array = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print("Printing 2D Array")
print(array)

print("Choose random row from a 2D array")
randomRow = np.random.randint(3, size=1)
print(array[randomRow[0], :])

print("Random item from random row is")
print(np.random.choice(array[randomRow[0], :]))

Printing 2D Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]
Choose random row from a 2D array
[11 22 33]
Random item from random row is
33


In [43]:
import numpy as np

array = [10, 20, 30, 40, 50, 20, 40]

x = np.random.choice(array, size=1)
print("single random choice from 1-D array", x)

items = np.random.choice(array, size=3, replace=False)
print("multiple random choice from numpy 1-D array without replacement ", items)

choices = np.random.choice(array, size=3, replace=True)
print("multiple random choices from numpy 1-D array with replacement ", choices)

single random choice from 1-D array [40]
multiple random choice from numpy 1-D array without replacement  [40 40 10]
multiple random choices from numpy 1-D array with replacement  [40 20 20]


In [44]:
import random

movie_list = ['The Godfather', 'The Wizard of Oz', 'Citizen Kane', 'The Shawshank Redemption', 'Pulp Fiction']
# secure random generator
secure_random = random.SystemRandom()
item = secure_random.choice(movie_list)
print (item)
# Output 'The Godfather'

The Wizard of Oz


In [45]:
import random

float_list = [22.5, 45.5, 88.5, 92.5, 55.4]
for i in range(5):
    # seed the random number generator
    random.seed(4)
    # print random item
    print(random.choice(float_list))


45.5
45.5
45.5
45.5
45.5


In [46]:
import random

# custom class
class studentData:
    def __init__(self, name, age):
        self.name = name
        self.age = age


jhon = studentData("John", 18)
emma = studentData("Emma", 19)

object_list = [jhon, emma]

# pick list index randomly using randint()
i = random.randint(0, len(object_list) - 1)
# Randomly select object from the given list of custom class objects
obj = object_list[i]
print(obj.name, obj.age)
# Output John 18

Emma 19


In [47]:
import random

aList = [20, 40, 80, 100, 120]
sampled_list = random.sample(aList, 3)
print(sampled_list)
# Output [20, 100, 80]

[20, 100, 40]


In [48]:
import random

exampleList = [20, 40, 20, 20, 40, 60, 70]
# choosing 4 random items from a list
sampled_list2 = random.sample(exampleList, 4)
print(sampled_list2)
# Output [60, 20, 20, 40]

[40, 20, 60, 40]


In [49]:
import random

names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]
# choose three random sample with replacement to including repetition
sample_list3 = random.choices(names, k=3)
print(sample_list3)
# output ['Martina', 'Nadal', 'Martina']

['Novac', 'Martina', 'Mariya']


In [50]:
import random

# create list of 5 random numbers
num_list = random.sample(range(100), 5)
print(num_list)
# output [79, 49, 6, 4, 57]

[97, 7, 28, 66, 68]


In [51]:
import random

# create list of 5 numbers
num_list = random.sample(range(100), 10)
random.shuffle(num_list)
print(num_list)
# output [90, 36, 63, 37, 23, 11, 30, 68, 99, 5]

[34, 35, 3, 46, 27, 33, 82, 13, 99, 22]


In [59]:
import random

aSet = {"Jhon", "kelly", "Scoot", "Emma", "Eric"}
# random 3 samples from set
sampled_set = random.sample(sorted(aSet), 3)
print(sampled_set)
# Output ['Emma', 'kelly', 'Eric']

['Jhon', 'kelly', 'Scoot']


In [61]:
import random

marks_dict = {
    "Kelly": 55,
    "jhon": 70,
    "Donald": 60,
    "Lennin": 50
}
sampled_dict = random.sample(sorted(marks_dict.items()), 2)
print(sampled_dict)
# Output [('Donald', 60), ('jhon', 70)]

# Access key-value from sample
# First key:value
print(sampled_dict[0][0], sampled_dict[0][1])
# Output jhon 70

# Second key:value
print(sampled_dict[1][0], sampled_dict[1][1])
# output Kelly 55

[('Kelly', 55), ('jhon', 70)]
Kelly 55
jhon 70


In [62]:
import random

# Randomly select same sample list every time
alist = [20.5, 40.5, 30.5, 50.5, 70.5]

for i in range(3):
    # use 4 as a seed value
    random.seed(4)
    # get sample list of three item
    sample_list = random.sample(alist, 3)
    print(sample_list)

[40.5, 30.5, 20.5]
[40.5, 30.5, 20.5]
[40.5, 30.5, 20.5]


In [63]:
import numpy

array = numpy.array([[2, 4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]])
print("Printing 2D Array")
print(array)

print("Choose 3 sample rows from 2D array")
randomRows = numpy.random.randint(5, size=2)
for i in randomRows:
    print(array[i, :])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Choose 3 sample rows from 2D array
[ 7 14 21]
[ 6 12 18]


In [64]:
import random

sampleList = [10, 20, 30, 40]
x = random.choice(sampleList)
print(x)

40


In [65]:
import random

numberList = [111, 222, 333, 444, 555]
print(random.choices(numberList, weights=(10, 20, 30, 40, 50), k=5))
# Output [555, 222, 555, 222, 555]

[444, 222, 111, 444, 333]


In [66]:
import random

nameList = ["Kelly", "Scott", "Emma", "Jon"]
print(random.choices(nameList, cum_weights=(5, 15, 30, 50), k=4))
# Output ['Jon', 'Kelly', 'Jon', 'Scott']

['Jon', 'Kelly', 'Emma', 'Emma']


In [67]:
import random

names = ["Kelly", "Scott", "Emma", "Jon"]
for i in range(3):
    item = random.choices(names, cum_weights=(5, 15, 30, 50), k=1)
    print("Iteration:", i, "Weighted Random choice is", item[0])

Iteration: 0 Weighted Random choice is Jon
Iteration: 1 Weighted Random choice is Jon
Iteration: 2 Weighted Random choice is Scott


In [68]:
import random

# we specified head and tail of a coin in string
coin = "HT"
# Execute 3 times to verify we are getting 6 or more heads in every 10 spins
for i in range(3):
    print(random.choices(coin, cum_weights=(0.61, 1.00), k=10))

['T', 'H', 'T', 'H', 'H', 'H', 'H', 'T', 'T', 'T']
['H', 'T', 'H', 'H', 'H', 'H', 'H', 'T', 'T', 'T']
['T', 'H', 'H', 'T', 'H', 'T', 'H', 'H', 'H', 'H']


In [69]:
import random

# Generate 6 random numbers from a given range with weighted probability
numbers = random.choices(range(10, 40, 5), cum_weights=(5, 15, 10, 25, 40, 65), k=6)
print(numbers)
# Output [35, 35, 15, 10, 35, 35]

[25, 25, 35, 15, 30, 35]


In [70]:
import numpy as np

numberList = [100, 200, 300, 400]
# Choose elements with different probabilities
sampleNumbers = np.random.choice(numberList, 4, p=[0.10, 0.20, 0.30, 0.40])
print(sampleNumbers)
# Output [300 200 300 300]


[200 300 400 400]


In [71]:
import random

# Always produces the same number with seed 30
print('Random number with seed 30')
for i in range(3):
    random.seed(30)
    print(random.randint(25, 50))

Random number with seed 30
42
42
42


In [72]:
import random

# Always produces the same number with seed 30
print('Random number with seed 30')
for i in range(2):
    print('Run', i,":")
    random.seed(30)
    for j in range(3):
        print(j, ":", random.randint(25, 50));

Random number with seed 30
Run 0 :
0 : 42
1 : 50
2 : 34
Run 1 :
0 : 42
1 : 50
2 : 34


In [73]:
import random

# # Generate a random sequence of elements
# Always shuffles in the same way with seed 30
for i in range(2):
    random.seed(30)
    my_list = [10, 20, 30, 40, 50]
    random.shuffle(my_list)
    print(my_list)

[20, 10, 40, 30, 50]
[20, 10, 40, 30, 50]


In [74]:
import random

random.seed(30)
print("first Number", random.randint(25, 50))

# generates a different random number
print("Second Number ", random.randint(25, 50))

# will generate a same random number as first one because seed value is same
random.seed(30)
print("Third Number", random.randint(25, 50))

first Number 42
Second Number  50
Third Number 42


In [77]:
import random
from datetime import datetime

# Random number with system time
random.seed(datetime.now().timestamp())
print("Random Number", random.randint(25, 50))
# Output 50

Random Number 31


In [78]:
import random
import sys

# create a seed
seed_value = random.randrange(sys.maxsize)
# save this seed somewhere. So if you like the result you can use this seed to reproduce it
print('Seed value:', seed_value)
# Output 4542355562136458828

# Now, Seed the random number generator
random.seed(seed_value)
num = random.randint(10, 500)
print("Random Number", num)
# Output 404

Seed value: 3748845175208714666
Random Number 429


In [79]:
import random

# Seed the random number generator with your value
random.seed(4542355562136458828)

num = random.randint(10, 500)
print("Random Number", num)
# Output 404

Random Number 404


In [80]:
import random

# Random seed with randrange
random.seed(350)
print(random.randrange(300, 500))
# output 336

random.seed(350)
print(random.randrange(300, 500))
# Output 336

392
392


In [81]:
import random
names = ["Alex", "Emma", "Kelly", "Scott", "Jessa"]

random.seed(50)
random_item = random.choice(names)
print ("First random name from list ", random_item)
# output scott

random.seed(50)
random_item = random.choice(names)
print ("Second random name from list ", random_item)
# output Scott

First random name from list  Scott
Second random name from list  Scott


In [82]:
import random

# using random.seed() and random.sample() together
fruit_list = ["Apple", "Mango", "Banana", "Apricot", "Cherries", "Grape", "Kiwi"]

random.seed(3)
sample_list = random.sample(fruit_list, 3)
print("First sample fruit list ", sample_list)
# Output ['Mango', 'Cherries', 'Grape']

random.seed(3)
sample_list = random.sample(fruit_list, 3)
print("Second sample fruit list ", sample_list)
# output ['Mango', 'Cherries', 'Grape']

First sample fruit list  ['Mango', 'Cherries', 'Grape']
Second sample fruit list  ['Mango', 'Cherries', 'Grape']


In [83]:
import random

numbers = [10, 20, 30, 40, 50, 60]
print("Original list: ", numbers)
random.seed(4)
random.shuffle(numbers)
print("Shuffled list ", numbers)
# Output [40, 60, 50, 10, 30, 20]

random.seed(4)
random.shuffle(numbers)
print("Reshuffled list ", numbers)
# Output [40, 60, 50, 10, 30, 20]

Original list:  [10, 20, 30, 40, 50, 60]
Shuffled list  [40, 60, 50, 10, 30, 20]
Reshuffled list  [10, 20, 30, 40, 50, 60]


In [84]:
import random

number_list = [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
# Original list
print(number_list)
# Output [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]

# List after first shuffle
random.shuffle(number_list)
print(number_list)
# Output [42, 28, 14, 21, 7, 35, 49, 63, 56, 70]

# List after second shuffle
random.shuffle(number_list)
print(number_list)
# Output [14, 21, 70, 28, 49, 35, 56, 7, 42, 63]


[7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
[70, 35, 42, 63, 28, 49, 7, 14, 21, 56]
[14, 63, 28, 7, 70, 35, 42, 49, 56, 21]


In [85]:
import random

numbers = [33, 66, 99, 188, 256, 412, 748]
# copy to new list
new_list = numbers.copy()
# shuffle the new list
random.shuffle(new_list)

print("Original list : ", numbers)
#  [33, 66, 99, 188, 256, 412, 748]

print("List after shuffle", new_list)
# Output [188, 412, 33, 256, 66, 748, 99]

Original list :  [33, 66, 99, 188, 256, 412, 748]
List after shuffle [66, 188, 33, 256, 99, 412, 748]


In [ ]:
import random
# custom class
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary
emp1 = Employee("Kelly", 10000)
emp2 = Employee("Abigail", 8000)
emp3 = Employee("Sampson", 12000)
emp4 = Employee("Joe", 7000)
# list with 4 objects
emp_list = [emp1, emp2, emp3, emp4]

# print original list
for emp in emp_list:
    print(emp.name, emp.salary, end=', ')
# Output Kelly 10000, Abigail 8000, Sampson 12000, Joe 7000,

# shuffle list of objects
# sample size (k) = length of a list
shuffledList = random.sample(emp_list, k=len(emp_list))
print("\nPrinting new shuffled list of employee object")
for emp in shuffledList:
    print(emp.name, emp.salary, end=', ')
# Output Joe 7000, Kelly 10000, Abigail 8000, Sampson 12000,


Kelly 10000, Abigail 8000, Sampson 12000, Joe 7000, 
Printing new shuffled list of employee object
Sampson 12000, Abigail 8000, Joe 7000, Kelly 10000, 

In [ ]:
import random
# list of names
employees = ['Jon', 'Emma', 'Kelly', 'Jason']
# list of numbers
salary = [7000, 6500, 9000, 10000]
# Lists before Shuffling
print("Employee Names: ", employees)
# output ['Jon', 'Emma', 'Kelly', 'Jason']
print("Employee Salaries: ", salary)
# Output [7000, 6500, 9000, 10000]

# To Shuffle two List at once with the same order
mapIndexPosition = list(zip(employees, salary))
random.shuffle(mapIndexPosition)
# make list separate
list1_names, list2_salary = zip(*mapIndexPosition)

# Lists after Shuffling
print("Employee Names: ", list1_names)
# Output ('Emma', 'Jon', 'Kelly', 'Jason')
print("Employee Salary: ", list2_salary)
# output (6500, 7000, 9000, 10000)

# Employee name and salary present index 3
print(list1_names[3], list2_salary[3])
# Output Jason 10000

Employee Names:  ['Jon', 'Emma', 'Kelly', 'Jason']
Employee Salaries:  [7000, 6500, 9000, 10000]
Employee Names:  ('Jon', 'Emma', 'Jason', 'Kelly')
Employee Salary:  (7000, 6500, 10000, 9000)
Kelly 9000


In [ ]:
import numpy as np
print('Before shuffling 2dimensional array')
sample_array = np.arange(100, 240, 10)
sample_array = sample_array.reshape(7, 2)
print(sample_array)

print('After shuffling 2dimensional array')
np.random.shuffle(sample_array)
print(sample_array)


Before shuffling 2dimensional array
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]
 [200 210]
 [220 230]]
After shuffling 2dimensional array
[[120 130]
 [140 150]
 [160 170]
 [220 230]
 [180 190]
 [100 110]
 [200 210]]


In [89]:
import random

numbers = [10, 20, 30, 40, 50, 60]
print("Original list: ", numbers)

# shuffle 3 times
for i in range(3):
    # seed PRNG
    random.seed(4)
    # shuffle list
    random.shuffle(numbers)
    print("result list ", numbers)


Original list:  [10, 20, 30, 40, 50, 60]
result list  [40, 60, 50, 10, 30, 20]
result list  [10, 20, 30, 40, 50, 60]
result list  [40, 60, 50, 10, 30, 20]


In [90]:
import random

string_one = "PYnative"
random.shuffle(string_one)
print(string_one)
# TypeError: 'str' object does not support item assignment.

TypeError: 'str' object does not support item assignment

In [91]:
import random

sample_str = "PYnative"
# Original string
print(sample_str)
# 'PYnative'

# convert string into list
char_list = list(sample_str)
# shuffle list
random.shuffle(char_list)

# convert list to string
final_str = ''.join(char_list)

# shuffled list
print(final_str)
# Output 'tiaeYPvn'


PYnative
tYeaivPn


In [92]:
import random

sample_str = "PYnative"
print(sample_str)
# 'PYnative'

# shuffle string using random.sample()
final_str = ''.join(random.sample(sample_str, len(sample_str)))
print(final_str)
# Output 'ePtaYivn'

PYnative
PYtinvea


In [93]:
import random

# Shuffle a range of numbers
numbers = list(range(10))
random.shuffle(numbers)
print(numbers)
# Output [1, 7, 0, 3, 2, 9, 6, 8, 4, 5]

[1, 8, 7, 9, 2, 5, 6, 0, 3, 4]


In [94]:
import random

student_dict = {'Eric': 80, 'Scott': 75, 'Jessa': 95, 'Mike': 66}
print("Dictionary Before Shuffling")
print(student_dict)
keys = list(student_dict.keys())
random.shuffle(keys)

ShuffledStudentDict = dict()
for key in keys:
    ShuffledStudentDict.update({key: student_dict[key]})

print("\nDictionary after Shuffling")
print(ShuffledStudentDict)


Dictionary Before Shuffling
{'Eric': 80, 'Scott': 75, 'Jessa': 95, 'Mike': 66}

Dictionary after Shuffling
{'Eric': 80, 'Mike': 66, 'Scott': 75, 'Jessa': 95}


In [95]:
import random

def sample_generator():
    yield 25
    yield 50
    yield 75
    yield 100

print("Generator")
for i in sample_generator():
    print(i, end=", ")

# Shuffle generator
newList = list(sample_generator())
random.shuffle(newList)
print("\nPrint shuffled generator")
for i in newList:
    print(i, end=", ")

Generator
25, 50, 75, 100, 
Print shuffled generator
100, 50, 75, 25, 

In [96]:
import random

x = random.random()
# Random float number
for i in range(3):
    print(random.random())


0.5059537757104153
0.17779017424078447
0.47358788758514514


In [97]:
import random

# Random float number between range 10.5 to 75.5
print(random.uniform(10.5, 75.5))
# Output 27.23469913175497

# between 10 and 100
print(random.uniform(10, 100))
# Output 81.77036292015993

16.30750347225037
94.11295275099172


In [98]:
import random

# Random float number with 2 decimal places
print(round(random.random(), 2))
# Output 0.21

print(round(random.uniform(33.33, 66.66), 2))
# Output 62.0

# With 1 decimal places
print(round(random.random(), 1))
# Output 0.3

print(round(random.uniform(33.33, 66.66), 1))
# Output 54.6

0.87
51.58
0.3
63.6


In [99]:
import random
import decimal

# random decimal
x = decimal.Decimal(str(random.uniform(100, 1000)))
print(x)
# Output 936.3682817788443

615.1301215173023


In [100]:
import random

# random float from 1 to 99.9
int_num = random.choice(range(10, 1000))
float_num = int_num/10
print(float_num)
# Output 81.2

91.3


In [101]:
import random

random_float_list = []
# Set a length of the list to 10
for i in range(0, 10):
    # any random float between 50.50 to 500.50
    # don't use round() if you need number as it is
    x = round(random.uniform(50.50, 500.50), 2)
    random_float_list.append(x)

print(random_float_list)
# Output [98.01, 454.48, 117.69, 51.44, 415.01, 455.52, 65.39, 385.07, 112.38, 434.1]

[190.79, 394.84, 138.31, 241.18, 180.19, 253.62, 155.45, 167.34, 409.33, 86.98]


In [102]:
import random

# random float from 1 to 99.9
int_num = random.choice(range(10, 1000))
float_num = int_num/10
print(float_num)
# Output 81.2

48.3


In [103]:
import random

random_float_list = []
# Set a length of the list to 10
for i in range(0, 10):
    # any random float between 50.50 to 500.50
    # don't use round() if you need number as it is
    x = round(random.uniform(50.50, 500.50), 2)
    random_float_list.append(x)

print(random_float_list)
# Output [98.01, 454.48, 117.69, 51.44, 415.01, 455.52, 65.39, 385.07, 112.38, 434.1]

[332.36, 176.69, 291.08, 262.56, 204.78, 499.28, 138.51, 236.26, 141.7, 335.2]


In [104]:
import random

list_Size = 10
# random float from 1 to 99.9
integer_list = random.sample(range(10, 1000), list_Size)
float_list = [x/10 for x in integer_list]
print(float_list)
# Output [7.9, 84.6, 72.1, 92.9, 64.1, 2.8, 32.6, 36.9, 97.4, 64.4]

[29.2, 19.8, 37.4, 45.6, 77.4, 61.2, 33.8, 65.9, 58.1, 21.3]


In [105]:
import random

def get_float_list(start, stop, size):
    result = []
    unique_set = set()
    for i in range(size):
        x = round(random.uniform(start, stop),2)
        while x in unique_set:
            x = round(random.uniform(start, stop),2)
        unique_set.add(x)
        result.append(x)

    return result

print("List of unique random numbers between 100, 1000")
print(get_float_list(100, 1000, 10))

# Output [918.45, 544.86, 595.18, 830.98, 516.11, 531.88, 255.85, 727.47, 687.23, 558.28]

List of unique random numbers between 100, 1000
[913.88, 190.88, 155.45, 305.98, 788.65, 653.89, 313.68, 397.96, 259.79, 513.12]


In [106]:
import random

secure_random = random.SystemRandom()

randomfloat = secure_random.random()
print(randomfloat)
# output 0.800760229291861

randomfloat = secure_random.uniform(12.5, 77.5)
print(randomfloat)
# Output 35.0470859352744

0.2598507790583263
47.914410229372436


In [107]:
import numpy as np

random_float = np.random.randn()
print(random_float)
# Output 0.833280610141848

1.207044648440931


In [108]:
import numpy as np

random_float_number = np.random.uniform(49.5, 99.5)
print(random_float_number)
# Output 59.11713060647423

89.42575137393376


In [109]:
import numpy

random_float_array = numpy.random.rand(2, 3)
# Random float array 2X3
print(random_float_array,"\n")


[[0.04695316 0.90860035 0.09885335]
 [0.79153523 0.04630442 0.39693784]] 



In [110]:
import numpy

#2X2 random float
random_float_array = numpy.random.uniform(75.5, 125.5, size=(2, 2))
print(random_float_array)

[[ 91.41152165  86.59797809]
 [ 98.0997718  123.26963174]]


In [111]:
import random
import string

def get_random_string(length):
    # choose from all lowercase letter
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    print("Random string of length", length, "is:", result_str)

get_random_string(8)
get_random_string(6)
get_random_string(4)

Random string of length 8 is: blwcjxvk
Random string of length 6 is: akjkey
Random string of length 4 is: untv


In [112]:
import random
import string

def get_random_string(length):
    # With combination of lower and upper case
    result_str = ''.join(random.choice(string.ascii_letters) for i in range(length))
    # print random string
    print(result_str)

# string of length 8
get_random_string(8)
get_random_string(8)

esNmCsiq
yMkvKaxc


In [113]:
import random

# Random string of length 5
result_str = ''.join((random.choice('abcdxyzpqr') for i in range(5)))
print(result_str)
# Output ryxay

pcyyx


In [114]:
import random
import string

for i in range(3):
    # get random string of length 6 without repeating letters
    result_str = ''.join(random.sample(string.ascii_lowercase, 8))
    print(result_str)

sdognwyb
bzxftevy
rpshkbdq


In [115]:
import random
import string

# get random password pf length 8 with letters, digits, and symbols
characters = string.ascii_letters + string.digits + string.punctuation
password = ''.join(random.choice(characters) for i in range(8))
print("Random password is:", password)

Random password is: L0@z9zE4


In [116]:
import random
import string

password = ''.join(random.choice(string.printable) for i in range(8))
print("Random password is:", password)

Random password is: Q!4sRUv?


In [ ]:
import random
import string
def get_random_password():
    random_source = string.ascii_letters + string.digits + string.punctuation
    # select 1 lowercase
    password = random.choice(string.ascii_lowercase)
    # select 1 uppercase
    password += random.choice(string.ascii_uppercase)
    # select 1 digit
    password += random.choice(string.digits)
    # select 1 special symbol
    password += random.choice(string.punctuation)

    # generate other characters
    for i in range(6):
        password += random.choice(random_source)
    password_list = list(password)
    # shuffle all characters
    random.SystemRandom().shuffle(password_list)
    password = ''.join(password_list)
    return password

print("First Random Password is ", get_random_password())
# output  qX49}]Ru!(
print("Second Random Password is ", get_random_password())
# Output  3nI0.V#[T

First Random Password is  G&-e7eGnGF
Second Random Password is  HYO+3_Psgg


In [118]:
import secrets
import string

# secure random string
secure_str = ''.join((secrets.choice(string.ascii_letters) for i in range(8)))
print(secure_str)
# Output QQkABLyK

# secure password
password = ''.join((secrets.choice(string.ascii_letters + string.digits + string.punctuation) for i in range(8)))
print(password)
# output 4x]>@;4)

EDmDLYCH
stdgegd@


In [119]:
import random
import string

# get random string of letters and digits
source = string.ascii_letters + string.digits
result_str = ''.join((random.choice(source) for i in range(8)))
print(result_str)
# Output vZkOkL97

hKz95PP3


In [120]:
import random
import string

def get_string(letters_count, digits_count):
    letters = ''.join((random.choice(string.ascii_letters) for i in range(letters_count)))
    digits = ''.join((random.choice(string.digits) for i in range(digits_count)))

    # Convert resultant string to list and shuffle it to mix letters and digits
    sample_list = list(letters + digits)
    random.shuffle(sample_list)
    # convert list to string
    final_string = ''.join(sample_list)
    print('Random string with', letters_count, 'letters', 'and', digits_count, 'digits', 'is:', final_string)

get_string(5, 3)
# Output get_string(5, 3)

get_string(6, 2)
# Output Random string with 6 letters and 2 digits is: 7DeOCm5t


Random string with 5 letters and 3 digits is: Y66VTF1c
Random string with 6 letters and 2 digits is: H5nPuZA4


In [121]:
import secrets
print("Secure hexadecimal string token", secrets.token_hex(32))

Secure hexadecimal string token 9433f98d9b60716969106734c29f188b82217bbc404fc6a7b0452761952eef40


In [122]:
import uuid
stringId  = uuid.uuid4()
print("Secure unique string id", stringId)
# Output 0682042d-318e-45bf-8a16-6cc763dc8806

Secure unique string id bae032eb-1369-42f6-8bef-dc3ca62212e3


In [124]:
import strgen

random_str = strgen.StringGenerator("[\w\d]{10}").render()
print(random_str)
# Output 4VX1yInC9S

random_str2 = strgen.StringGenerator("[\d]{3}&[\w]{3}&[\p]{2}").render()
print(random_str2)
# output "C01N=10

5Y505zTy0r
2%0|Uzy4


<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:7: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:7: SyntaxWarning: invalid escape sequence '\d'
C:\Users\blokes\AppData\Local\Temp\ipykernel_22384\680784912.py:3: SyntaxWarning: invalid escape sequence '\w'
  random_str = strgen.StringGenerator("[\w\d]{10}").render()
C:\Users\blokes\AppData\Local\Temp\ipykernel_22384\680784912.py:7: SyntaxWarning: invalid escape sequence '\d'
  random_str2 = strgen.StringGenerator("[\d]{3}&[\w]{3}&[\p]{2}").render()


In [125]:
import os

data = os.urandom(5)
print("secure data from os.urandom ", data)
# Output  b'\n4.F\x08'

secure data from os.urandom  b']\xdd\xf2\tp'


In [ ]:
import os
import struct
# random integer using os.urandom()
print(struct.unpack('i', os.urandom(4)))
# Output (258871565,)

# unsigned random integer using os.urandom()
print(struct.unpack('I', os.urandom(4)))
print(struct.unpack('I', os.urandom(4))[0] % 100)
# Output (1015967885,)

# random short number using os.urandom()
print(struct.unpack('h', os.urandom(2)))
# Output (-28882,)

# unsigned random short using os.urandom()
print(struct.unpack('H', os.urandom(2)))
# Output (29492,)

# Print random float using os.urandom()
print(struct.unpack('f', os.urandom(4)))
# Output (-4.651611836498911e+20,)

# un-singed random decimal using os.urandom()
print(struct.unpack('d', os.urandom(8)))
# Output (-1.7024488468332834e-120,)

# random char using os.urandom()
print(struct.unpack('c', os.urandom(1)))
# Output (b'\xce',)

(-1229814095,)
(2438192042,)
11
(-25293,)
(55270,)
(-6.2979266587030116e+35,)
(4.579947099392454e-140,)
(b'\x08',)


In [ ]:
import random
# getting systemRandom instance out of random class
system_random = random.SystemRandom()

# Secure random number
print(system_random.randint(1, 30))
# Output 22

# Secure random number within a range
print(system_random.randrange(50, 100))
# Output 59

# secure random choice
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(system_random.choice(list1))
# Output 9

# secure random sample
print(system_random.sample(list1, 3))
# Output [1, 4, 9]

# secure random float
print(system_random.uniform(5.5, 25.5))
# Output 18.666415244982193

12
56
10
[8, 10, 7]
20.529647606191237


In [128]:
import secrets

print("Random integer number generated using secrets module is ")

number = secrets.randbelow(30)
print(number) # 27

number = secrets.randbelow(30)
print(number) # 20

Random integer number generated using secrets module is 
15
9


In [129]:
import secrets

# Getting systemRandom class instance out of secrets module
secretsGenerator = secrets.SystemRandom()

# secure random integer numbers
random_number = secretsGenerator.randint(0, 50)
print(random_number)
# Output 38

# secure random integer number within given
random_number2 = secretsGenerator.randrange(4, 40, 4)
print(random_number2)
# Output 32

# Secure Random choice using secrets
number_list = [6, 12, 18, 24, 30, 36, 42, 48, 54, 60]
secure_choice = secretsGenerator.choice(number_list)
print(secure_choice)
# Output 60

# Secure Random sample
secure_sample = secretsGenerator.sample(number_list, 3)
print(secure_sample)
# output [12, 42, 48]

# Secure Random float number
secure_float = secretsGenerator.uniform(2.5, 25.5)
print(secure_float)
# Output 18.062235454990407

49
12
24
[60, 12, 36]
19.64636833216719


In [130]:
import secrets

# secure Random integer number
for i in range(3):
    print(secrets.randbelow(10), end=', ')
# Output 0, 8, 6,

2, 7, 0, 

In [131]:
import secrets

name = "GuidoVanRossum"
# secrets choice from string is
print(secrets.choice(name))
# Output 'm'

name_list = ["Guido Van Rossum", "Bjarne Stroustrup", "Dennis Ritchie"]
# secure choice from list
print(secrets.choice(name_list))
# Output 'Bjarne Stroustrup'


d
Dennis Ritchie


In [132]:
import secrets

# using 4 bits
print(secrets.randbits(4))
# output 7

# using 8 bits
print(secrets.randbits(8))
# output 73

# using 16 bits
print(secrets.randbits(16))
# Output 509

# using 32 bits
print(secrets.randbits(32))
# Output 2740049514

1
30
40772
3159223598


In [133]:
import secrets

# secure byte token
print(secrets.token_bytes(16))

# secure hexadecimal token
print(secrets.token_hex(32))

# generate secure URLs
passwordResetLink = "demo.com/customer/eric/reset="
passwordResetLink += secrets.token_urlsafe(32)
print(passwordResetLink)


b'\xa3\x07\xfd\xab\xb2\x9a\xd4S0\xe7\xac\xaa\xbcJ\xa2n'
0554a6d04129806359036bae3953e4a57f248de60f29ea5917484d00e179f1cf
demo.com/customer/eric/reset=jaE3ZkmxdRt_gNN8UK76LjbSzQy0w52HJHAHpKOLW_k


In [ ]:
import secrets
import string
stringSource = string.ascii_letters + string.digits + string.punctuation
password = secrets.choice(string.ascii_lowercase)
password += secrets.choice(string.ascii_uppercase)
password += secrets.choice(string.digits)
password += secrets.choice(string.punctuation)

for i in range(6):
    password += secrets.choice(stringSource)

char_list = list(password)
secrets.SystemRandom().shuffle(char_list)
password = ''.join(char_list)
print("Secure Password is ", password)
# Output ^Kk58nL\(A
print("Ppassword Reset URL Link")
SecureURL = "https://demo.com/user/jhon/reset="
SecureURL += secrets.token_urlsafe(32)
print(SecureURL)
# https://demo.com/user/jhon/reset=Td3pRv_USCHfxQsBF0SFejEEFPp1NLaHBkbzth5gRjQ

Secure Password is  bm6AvzIi:8
Ppassword Reset URL Link
https://demo.com/user/jhon/reset=zGimeT6Z16tVyTUJynYRnvu7ad0WgsnyKEjZDTcmc2Q


In [135]:
import uuid
# Generate a UUID from a host ID, sequence number, and the current time
uuidOne = uuid.uuid1()
print("UUID of version one", uuidOne)

UUID of version one 3238a8f5-0b06-11f0-b988-94e23cef6852


In [136]:
import uuid

# Generate a UUID using a clock sequence and node

print("UUID of version one")
clock_seq = 4115

for node in [0xccaf789d94a0, 0xadaf456d94a0]:
    print(uuid.uuid1(node, clock_seq))

UUID of version one
690d15f5-0b06-11f0-9013-ccaf789d94a0
690d15f6-0b06-11f0-9013-adaf456d94a0


In [137]:
import uuid

# Get the hardware address as a 48-bit positive integer
print("MAC address integer format", uuid.getnode())
print("MAC address Hex format", hex(uuid.getnode()))

MAC address integer format 163699405842514
MAC address Hex format 0x94e23cef6852


In [138]:
import uuid

for i in range(2):
    uuidFour = uuid.uuid4()
    print("uuid of version four", uuidFour)

uuid of version four 7cdac466-a46a-419e-914d-0eb23af94287
uuid of version four 1dc0d4a5-d454-49dd-94b4-a91cb7722c77


In [139]:
import uuid

hostNames = ['google.com', 'stackoverflow.com']

for host in hostNames:
    print('Generate uuid of version 3 using name as',host,' and namespace as uuid.NAMESPACE_DNS')
    print(uuid.uuid3(uuid.NAMESPACE_DNS, host))
    print('Generate uuid of version 5 using name as', host, ' and namespace as uuid.NAMESPACE_DNS'),
    print(uuid.uuid5(uuid.NAMESPACE_DNS, host))
    print()

Generate uuid of version 3 using name as google.com  and namespace as uuid.NAMESPACE_DNS
9a74c83e-2c09-3513-a74b-91d679be82b8
Generate uuid of version 5 using name as google.com  and namespace as uuid.NAMESPACE_DNS
64ee70a4-8cc1-5d25-abf2-dea6c79a09c8

Generate uuid of version 3 using name as stackoverflow.com  and namespace as uuid.NAMESPACE_DNS
6d079ab3-a985-3dc7-8086-3dc32dc08cb9
Generate uuid of version 5 using name as stackoverflow.com  and namespace as uuid.NAMESPACE_DNS
cd84c40a-6019-50c7-87f7-178668ab9c8b



In [140]:
import uuid

nameSpaces = [uuid.NAMESPACE_DNS, uuid.NAMESPACE_URL, uuid.NAMESPACE_OID, uuid.NAMESPACE_X500]
hostName = 'google.com'
print("Generate uuid using namespace")

for namespace in nameSpaces:
    print('uuid 3 is', uuid.uuid3(namespace, hostName))
    print('uuid 5 is', uuid.uuid5(namespace, hostName))
    print()

Generate uuid using namespace
uuid 3 is 9a74c83e-2c09-3513-a74b-91d679be82b8
uuid 5 is 64ee70a4-8cc1-5d25-abf2-dea6c79a09c8

uuid 3 is 79f1759f-cdf0-3f6e-9f86-2330cb620388
uuid 5 is fedb2fa3-8f5c-5189-80e6-f563dd1cb8f9

uuid 3 is 5793eb88-93ca-37fc-a801-37a98bbf5b93
uuid 5 is 121a6e47-af67-5624-bc20-e50b22d260e2

uuid 3 is fe4b24a0-9a38-3b32-84ca-ae0935462bc9
uuid 5 is 51e12dff-dcaa-5885-ade2-05d719625376



In [141]:
import uuid

print('Generate uuid of version 3 using name as google.com and namespace as uuid.NAMESPACE_DNS')
print(uuid.uuid3(uuid.NAMESPACE_DNS, "google.com"))

print('Generate uuid of version 3 using name as google.com and namespace as uuid.NAMESPACE_DNS')
print(uuid.uuid3(uuid.NAMESPACE_DNS, "google.com"))

Generate uuid of version 3 using name as google.com and namespace as uuid.NAMESPACE_DNS
9a74c83e-2c09-3513-a74b-91d679be82b8
Generate uuid of version 3 using name as google.com and namespace as uuid.NAMESPACE_DNS
9a74c83e-2c09-3513-a74b-91d679be82b8


In [142]:
import uuid

UUID = uuid.uuid1()

print("UUID is ", UUID)
print("UUID Type is ",type(UUID))
print('UUID.bytes   :', UUID.bytes)
print('UUID.bytes_le :', UUID.bytes_le)
print('UUID.hex     :', UUID.hex)
print('UUID.int     :', UUID.int)
print('UUID.urn     :', UUID.urn)
print('UUID.variant :', UUID.variant)
print('UUID.version :', UUID.version)
print('UUID.fields  :', UUID.fields)
print("Prining each field seperately")
print('UUID.time_low            : ', UUID.time_low)
print('UUID.time_mid            : ', UUID.time_mid)
print('UUID.time_hi_version     : ', UUID.time_hi_version)
print('UUID.clock_seq_hi_variant: ', UUID.clock_seq_hi_variant)
print('UUID.clock_seq_low       : ', UUID.clock_seq_low)
print('UUID.node                : ', UUID.node)
print('UUID.time                : ', UUID.time)
print('UUID.clock_seq           : ', UUID.clock_seq)
print('UUID.SafeUUID           : ', UUID.is_safe)

UUID is  b0dd3f8a-0b08-11f0-a7a6-94e23cef6852
UUID Type is  <class 'uuid.UUID'>
UUID.bytes   : b'\xb0\xdd?\x8a\x0b\x08\x11\xf0\xa7\xa6\x94\xe2<\xefhR'
UUID.bytes_le : b'\x8a?\xdd\xb0\x08\x0b\xf0\x11\xa7\xa6\x94\xe2<\xefhR'
UUID.hex     : b0dd3f8a0b0811f0a7a694e23cef6852
UUID.int     : 235092913592586938794811584897499490386
UUID.urn     : urn:uuid:b0dd3f8a-0b08-11f0-a7a6-94e23cef6852
UUID.variant : specified in RFC 4122
UUID.version : 1
UUID.fields  : (2967289738, 2824, 4592, 167, 166, 163699405842514)
Prining each field seperately
UUID.time_low            :  2967289738
UUID.time_mid            :  2824
UUID.time_hi_version     :  4592
UUID.clock_seq_hi_variant:  167
UUID.clock_seq_low       :  166
UUID.node                :  163699405842514
UUID.time                :  139623720403419018
UUID.clock_seq           :  10150
UUID.SafeUUID           :  SafeUUID.unknown


In [143]:
import uuid

UUID1 = uuid.uuid1()
print("UUID of version 1 is ", UUID1)
# convert a UUID to a string of hex digits in standard form
print("UUID of version 1 in String format", str(UUID1))

UUID of version 1 is  2bebcc7f-0b09-11f0-882b-94e23cef6852
UUID of version 1 in String format 2bebcc7f-0b09-11f0-882b-94e23cef6852


In [144]:
import uuid

UUID1 = uuid.uuid1()
print("UUID of version 1 is ", UUID1)
# convert a UUID to a string of hex digits in standard form
uuidString = str(UUID1).replace("-", "")
print("UUID of version 1 in String removing dashes", uuidString)

UUID of version 1 is  7593f0f6-0b09-11f0-b113-94e23cef6852
UUID of version 1 in String removing dashes 7593f0f60b0911f0b11394e23cef6852


In [145]:
import uuid

UUIDStrings = ["{55da37d1-d481-11e8-9013-adaf456d94a0}", "018c168c-d509-11e8-b096-ccaf789d94a0", "urn:uuid:e5e9394c-daed-498e-b9f3-69228b44fbfa"]

for string in UUIDStrings:
    # make a UUID from a string of hex digits (braces and hyphens ignored)
    myUUID = uuid.UUID(string)
    print("My UUID is", myUUID)
    print("My UUID time component is", myUUID.time)
    print()

My UUID is 55da37d1-d481-11e8-9013-adaf456d94a0
My UUID time component is 137593440591034321

My UUID is 018c168c-d509-11e8-b096-ccaf789d94a0
My UUID time component is 137594023292180108

My UUID is e5e9394c-daed-498e-b9f3-69228b44fbfa
My UUID time component is 688728508333635916



In [146]:
import uuid

print("Generating UUID from int")
UUID_x = uuid.UUID(int=236357465324988601727440242910546465952)
print("UUID is", UUID_x)

print("UUID from URN")
UUID_x1 = uuid.UUID('urn:uuid:b1d0cac0-d50d-11e8-b57b-ccaf789d94a0')
print("UUID is", UUID_x1)

print("UUID from bytes")
UUID_x2 = uuid.UUID(bytes=b'\xb1\xd0\xca\xc0\xd5\r\x11\xe8\xb5{\xcc\xafx\x9d\x94\xa0')
print("UUID is", UUID_x2)

print("UUID from bytes_len")
UUID_x3 = uuid.UUID(bytes_le=b'\xc0\xca\xd0\xb1\r\xd5\xe8\x11\xb5{\xcc\xafx\x9d\x94\xa0')
print("UUID is", UUID_x3)

print("UUID from fields")
UUID_x4 = uuid.UUID(fields=(2983250624, 54541, 4584, 181, 123, 225054014936224))
print("UUID is", UUID_x4)

Generating UUID from int
UUID is b1d0cac0-d50d-11e8-b57b-ccaf789d94a0
UUID from URN
UUID is b1d0cac0-d50d-11e8-b57b-ccaf789d94a0
UUID from bytes
UUID is b1d0cac0-d50d-11e8-b57b-ccaf789d94a0
UUID from bytes_len
UUID is b1d0cac0-d50d-11e8-b57b-ccaf789d94a0
UUID from fields
UUID is b1d0cac0-d50d-11e8-b57b-ccaf789d94a0


In [150]:
import uuid
from faker import Faker

fakerObj = Faker()
Faker.seed(8754)
print(fakerObj.uuid4())

Faker.seed(8754)
print(fakerObj.uuid4())

02ee0340-e0ca-4baf-891f-d42f5aebc46f
02ee0340-e0ca-4baf-891f-d42f5aebc46f


In [151]:
import uuid

UUID1 = uuid.uuid1()
print("uuid 1 safety", UUID1.is_safe)

uuid 1 safety SafeUUID.unknown
